USE echommo_db;

-- 1. FLAVOR TEXT (Lời thoại, triết lý)
INSERT INTO flavor_text (content) VALUES
                                      ('Giang hồ hiểm ác, người cười ta quá ngốc, ta cười người nhìn không thấu.'),
                                      ('Một kiếm xuất vỏ, trời đất đổi thay.'),
                                      ('Trong chén rượu nhạt, chứa cả phong vân càn khôn.'),
                                      ('Kẻ mạnh không bao giờ giải thích.'),
                                      ('Gió thổi mây tan, anh hùng lộ diện.'),
                                      ('Có những nỗi đau chỉ kiếm mới thấu hiểu.'),
                                      ('Một đời hành tẩu, chỉ cầu hai chữ: tự do.'),
                                      ('Kiếm phong nơi tay, tâm không sợ hãi.'),
                                      ('Nhân tâm khó lường, giang hồ khó đoán.'),
                                      ('Bước vào giang hồ, thân bất do kỷ.'),
                                      ('Chân lý nằm ở cuối lưỡi kiếm.'),
                                      ('Thù này không báo, thề không đội trời chung.'),
                                      ('Một tiếng thở dài, gió lạnh đầy trời.'),
                                      ('Hữu duyên thiên lý năng tương ngộ, vô duyên đối diện bất tương phùng.'),
                                      ('Rượu càng cũ càng cay, người càng già càng lạnh.'),
                                      ('Giang hồ vốn không phụ ai, chỉ có người tự phụ mình.'),
                                      ('Chỉ có kẻ ngu mới không biết sợ, và kẻ mạnh mới không cần sợ.'),
                                      ('Một đời một kiếm, ngạo thị thiên hạ.'),
                                      ('Ân oán giang hồ, không phải muốn quên là quên được.'),
                                      ('Thắng làm vua, thua thành tro bụi.'),
                                      ('Sống không oán, chết không hối.'),
                                      ('Tử chiến đến cùng, máu nhuộm giang sơn.'),
                                      ('Một kiếm cắt đứt tình thù, nhưng không cắt được lòng mình.'),
                                      ('Giữa đêm dài, kiếm ngân lên tiếng gọi số mệnh.'),
                                      ('Đường dài mới biết ngựa hay, hoạn nạn mới biết bạn bè.'),
                                      ('Thiên hạ rộng lớn, nhưng không rộng bằng lòng người.'),
                                      ('Gian hùng một đời, đổi lấy một nấm đất.'),
                                      ('Nắm kiếm là sinh tử, buông kiếm là thành bại.'),
                                      ('Không vào hang hổ, sao bắt được hổ con.'),
                                      ('Gieo gió ắt gặp bão.'),
                                      ('Một giọt máu rơi, nghìn năm oán hận.'),
                                      ('Kiếm nghìn năm lạnh, chỉ chờ một người dùng đúng.'),
                                      ('Ngạo xương sống, thẳng làm người.'),
                                      ('Càn khôn xoay chuyển, vận mệnh do ta định.'),
                                      ('Rồng gặp mây thì bay, người gặp vận thì phát.'),
                                      ('Tâm bất động, vạn vật đều im.'),
                                      ('Một bước sai, vạn kiếp khó quay đầu.'),
                                      ('Kiếm là xương, khí là hồn, ý là mạng.'),
                                      ('Bất động như sơn, bạo phát như lôi.'),
                                      ('Trước mặt cường địch, lùi một bước là mất mạng.'),
                                      ('Nam tử chân chính, dám làm dám chịu.'),
                                      ('Đời người như gió, thoảng qua không dấu vết.'),
                                      ('Một niệm thành ma, một niệm thành thần.'),
                                      ('Chính tà chỉ cách nhau một đường tơ.'),
                                      ('Vận mệnh nằm trong tay kẻ có gan thay đổi nó.'),
                                      ('Càng tiến càng cô độc, đó là con đường cường giả.'),
                                      ('Mỗi vết sẹo là một câu chuyện chưa kể.'),
                                      ('Thời thế tạo anh hùng, anh hùng định thời thế.'),
                                      ('Ai cũng có bí mật, chỉ khác nhau là có đáng chết vì nó không.'),
                                      ('Hận vì yêu, đau vì tình.'),
                                      ('Giang hồ không phải chốn cho kẻ mộng mơ.'),
                                      ('Nửa đời phiêu bạt, đổi một lần quay đầu.'),
                                      ('Cừu sâu như biển, báo sao cho hết.'),
                                      ('Một thân một kiếm, trời tính sao ta tính vậy.'),
                                      ('Không phải ta không giết, chỉ là chưa đến lúc.'),
                                      ('Một đời một đạo, thuận theo thiên mệnh.'),
                                      ('Không ai vô tội trên giang hồ.'),
                                      ('Vô tình nhất không phải kiếm, mà là lòng người.'),
                                      ('Kẻ đáng sợ nhất là kẻ không còn gì để mất.'),
                                      ('Lưỡi kiếm vô tình, người cầm kiếm càng vô tâm.'),
                                      ('Chân chính mạnh mẽ là biết sợ hãi mà vẫn tiến lên.'),
                                      ('Biết mình biết ta, trăm trận trăm thắng.'),
                                      ('Tâm loạn thì kiếm loạn.'),
                                      ('Dựa núi thì núi đổ, dựa người thì người phản.'),
                                      ('Một chữ LỢI hại chết bao anh hùng.'),
                                      ('Chớ để lòng tốt đổi thành dao đâm chính mình.'),
                                      ('Tàn nhẫn với kẻ thù, khoan dung với bản thân.'),
                                      ('Phong vân biến hóa, mưu sâu khó lường.'),
                                      ('Cao thủ chân chính không cần khoe chiêu.'),
                                      ('Tĩnh để sinh trí, loạn để diệt thân.'),
                                      ('Không ai sống mãi, nhưng danh có thể.'),
                                      ('Muốn đứng trên vạn người, phải chịu cái lạnh của đỉnh cao.'),
                                      ('Thế gian hiểm ác, chỉ có bản thân là chỗ dựa.'),
                                      ('Người nói vô tâm, nhưng lòng ta hữu ý.'),
                                      ('Thâm tình không địch nổi vô duyên.'),
                                      ('Một nụ cười, giấu ngàn giọt lệ.'),
                                      ('Tâm nguyện chưa thành, chết cũng không yên.'),
                                      ('Thoắt vui thoắt buồn, đời như mây bay.'),
                                      ('Đao sắc không bằng tâm sắc.'),
                                      ('Thiên hạ này, kẻ khó thắng nhất là chính mình.'),
                                      ('Một ly rượu tiễn biệt, vạn dặm chẳng quay đầu.'),
                                      ('Trái tim mạnh nhất cũng có vết nứt.'),
                                      ('Sát khí ba phần, còn lại là bất đắc dĩ.'),
                                      ('Không thù không oán, nhưng ngươi phải chết.'),
                                      ('Lắm kẻ cười ta vì quá điên cuồng, ta cười bọn họ không dám sống.'),
                                      ('Sống vì mình một lần, chết cũng cam.'),
                                      ('Một chút nhân từ, đổi lấy một mạng người.'),
                                      ('Không cần biết ngươi là ai, ngươi cản ta là địch.'),
                                      ('Cái lạnh nhất không phải gió đêm, mà là lòng người.'),
                                      ('Cường giả luôn đi trong cô độc.'),
                                      ('Ai cũng muốn sống lâu, nhưng không ai dám sống đúng.'),
                                      ('Không thể tránh, vậy thì đối mặt.'),
                                      ('Kiếm sắc gặp kẻ mạnh, ý chí mới là thắng bại.'),
                                      ('Một câu nói sai, mất mạng như chơi.'),
                                      ('Đời người chỉ mong không thẹn với lòng.'),
                                      ('Muốn biết lòng người, cứ xem họ đối xử lúc nghèo khó.'),
                                      ('Người thắng cười lớn, kẻ thua hóa tro tàn.');

-- 2. WEATHER TEXT (Mô tả thời tiết)
INSERT INTO weather_text (content) VALUES
                                       ('Gió sớm thổi qua thung lũng, mang theo hơi lạnh của ngàn núi xa xăm.'),
                                       ('Mây trắng lững lờ, trôi như quên cả thời gian.'),
                                       ('Trời cao xanh lộng, chim bay không để lại dấu.'),
                                       ('Sương mờ phủ kín, che giấu mọi dấu vết của nhân gian.'),
                                       ('Hoàng hôn đỏ rực, nhuộm cả chân trời bằng sắc máu.'),
                                       ('Tiếng lá khô xào xạc, như lời thì thầm của rừng già.'),
                                       ('Sấm động phương xa, trời đất như chuẩn bị đổi thay.'),
                                       ('Đêm sâu, ánh trăng chiếu xuống mặt hồ tĩnh lặng không một gợn sóng.'),
                                       ('Gió núi gào thét, cuộn lên như tiếng của thiên địa.'),
                                       ('Bầu trời đen đặc, không thấy một ngôi sao.'),
                                       ('Sương đêm rơi trên mái ngói, lặng lẽ không tiếng động.'),
                                       ('Mưa phùn rơi nhẹ, phủ lên đất trời sắc u buồn.'),
                                       ('Cơn gió xuân thổi qua, mang theo hơi ấm hiếm hoi.'),
                                       ('Giữa trưa nắng cháy, mặt đất bốc hơi như sương mờ.'),
                                       ('Bình minh ló dạng, ánh sáng yếu ớt xuyên qua màn sương mỏng.'),
                                       ('Trăng non treo lơ lửng, như một lưỡi kiếm bạc nơi chân trời.'),
                                       ('Mặt trời dần khuất sau dãy núi, để lại bóng tối dài vô tận.'),
                                       ('Cả cánh rừng bỗng im bặt, như đang chờ điều gì đó xảy ra.'),
                                       ('Gió mang theo mùi của đất, của cỏ, của đại địa bao la.'),
                                       ('Tiếng nước chảy róc rách giữa khe suối nhỏ.'),
                                       ('Ánh trăng phản chiếu trên tuyết trắng, sáng đến chói mắt.'),
                                       ('Trời mưa tầm tã, tiếng nước dội xuống mái ngói nghe như trống trận.'),
                                       ('Mây mù bao phủ đỉnh núi, không thấy đường đi.'),
                                       ('Gió đêm lạnh buốt xuyên qua từng lớp áo.'),
                                       ('Nắng chiều hắt xuống, kéo dài những cái bóng vô tận.'),
                                       ('Đại dương gầm rống, sóng vỗ bờ như ngàn quân thét hét.'),
                                       ('Một cơn gió nhẹ thoảng qua, mang theo hương hoa dại.'),
                                       ('Mặt trời treo trên cao, chiếu xuống ánh sáng vàng rực rỡ.'),
                                       ('Bầu trời chuyển sắc, báo hiệu một cơn bão đang đến gần.'),
                                       ('Hơi nước bốc lên từ mặt đất, hòa vào ánh sáng mờ ảo.'),
                                       ('Không khí đặc quánh, như thể giông tố sắp ập đến.'),
                                       ('Gió đông lạnh giá thổi qua, khiến mọi sinh linh đều run rẩy.'),
                                       ('Mưa rơi không ngớt, từng giọt rơi như đinh găm xuống đất.'),
                                       ('Sấm chớp rạch ngang bầu trời, xé tan bóng tối.'),
                                       ('Ánh nắng xen qua tầng mây, chiếu xuống mặt đất ấm áp.'),
                                       ('Gió lặng, trời yên, chỉ nghe tiếng tim mình đập.'),
                                       ('Một dải cầu vồng mờ ảo hiện lên sau cơn mưa.'),
                                       ('Bầu trời trong vắt, cao đến mức như thể vô tận.'),
                                       ('Những chiếc lá vàng xoay vòng theo gió thu.'),
                                       ('Bụi mù cuộn lên theo bước chân, che mờ lối cũ.'),
                                       ('Sương núi dày đặc, tầm mắt chỉ còn vài bước.'),
                                       ('Khói lam chiều bốc lên từ những mái nhà xa xa.'),
                                       ('Không khí se lạnh như níu giữ từng hơi thở.'),
                                       ('Trời đất im lìm, đến cả tiếng côn trùng cũng biến mất.'),
                                       ('Một tia sáng lặng lẽ chiếu xuyên qua đám mây đen.'),
                                       ('Hoàng hôn nhuộm tím cả khoảng trời rộng lớn.'),
                                       ('Hơi sương bốc lên, tạo thành một màn mờ huyền ảo.'),
                                       ('Trăng tròn tỏa sáng, chiếu rõ từng nhành cây ngọn cỏ.'),
                                       ('Mặt đất rung chuyển nhẹ, báo hiệu điềm lạ sắp đến.'),
                                       ('Gió biển mang theo vị mặn thấm vào da thịt.'),
                                       ('Trong đêm tối, đom đóm bay lập lòe như tinh linh.'),
                                       ('Cát trên sa mạc bị gió cuốn thành từng lớp sóng vàng.'),
                                       ('Hồ nước phản chiếu cả bầu trời rộng lớn.'),
                                       ('Tảng mây đen lững lờ trôi, che khuất ánh trăng.'),
                                       ('Một cơn gió thoáng qua mang theo chút hơi ấm kỳ lạ.'),
                                       ('Không khí trong lành, tinh khiết đến mức nghe rõ từng hơi thở.'),
                                       ('Gió cuộn theo mùi của cỏ non và đất mới.'),
                                       ('Tia chớp xé ngang trời đêm như rạch đôi màn sương.'),
                                       ('Ánh sáng mờ nhạt từ bình minh nhuộm hồng đường chân trời.'),
                                       ('Lá rơi đầy sân, báo hiệu một mùa mới sắp đến.'),
                                       ('Hơi lạnh từ hang động thổi ra khiến sống lưng tê dại.'),
                                       ('Sương mù bám trên cỏ khiến mặt đất lấp lánh như có ngọc.'),
                                       ('Cơn mưa nhẹ làm mặt đường loang loáng phản chiếu ánh đèn.'),
                                       ('Trời đêm đầy sao, sáng như có ngọn lửa phía trên.'),
                                       ('Gió lốc xoáy lên từng vệt cát vàng bay khắp trời.'),
                                       ('Ráng chiều đỏ rực như cháy lan cả bầu trời.'),
                                       ('Dòng suối róc rách, mang âm thanh như tiếng đàn cổ.'),
                                       ('Bão cát nổi lên, che mờ cả mặt trời.'),
                                       ('Hương hoa thoang thoảng theo gió khiến lòng người nhẹ nhàng.'),
                                       ('Gió thu thoảng qua, mang theo cảm giác se lạnh dễ chịu.'),
                                       ('Hơi nóng bốc lên từ mặt đất, làm mọi thứ trở nên mờ ảo.'),
                                       ('Sóng biển vỗ bờ không ngừng, nghe như lời ru ngàn năm.'),
                                       ('Bầu trời âm u khiến lòng người cũng chùng xuống.'),
                                       ('Mặt trăng bị mây che khuất, để lại ánh sáng mờ mịt.'),
                                       ('Những tiếng gió hú xuyên qua rừng cây nghe như quỷ khóc.'),
                                       ('Nắng nhẹ rọi xuống những tán lá, tạo thành bóng đổ đẹp đến kỳ lạ.'),
                                       ('Không khí lạnh buốt khiến từng hơi thở đều hóa thành sương.'),
                                       ('Đêm tối sâu thẳm, cảm giác như có đôi mắt nào đó đang dõi theo.'),
                                       ('Gió mạnh thổi dùng dằng báo hiệu điềm chẳng lành.'),
                                       ('Hương thơm của đất sau mưa lan tỏa khắp thung lũng.'),
                                       ('Bụi mù che khuất cả bầu trời khi đàn thú phi nước đại qua đồng.'),
                                       ('Trời đổ nắng, ánh sáng chói lóa khiến người ta không mở nổi mắt.'),
                                       ('Những giọt sương long lanh như châu báu đọng trên lá.'),
                                       ('Không khí u ám bao trùm vùng đất như có lời nguyền.'),
                                       ('Tiếng nước vỗ vào vách đá tạo thành âm thanh vang dội.'),
                                       ('Bầu trời lặng gió, khiến lòng người bất giác lo sợ.'),
                                       ('Cánh đồng rộng lớn bị gió thu quét qua thành sóng lúa dập dờn.'),
                                       ('Tuyết rơi trắng xóa, phủ đầy trời đất như tấm thảm bạc.'),
                                       ('Gió cuốn bụi đường bay mù mịt khắp lối.'),
                                       ('Trời vừa mưa xong, ánh cầu vồng xuất hiện đầy rực rỡ.'),
                                       ('Không khí phảng phất mùi hương hoa quỳnh nở về đêm.'),
                                       ('Mặt trời dần lên, sưởi ấm từng phiến đá lạnh lẽo.'),
                                       ('Đêm tối yên ắng, chỉ nghe tiếng côn trùng kêu nhịp nhàng.'),
                                       ('Gió mùa đông lạnh lẽo, len lỏi qua từng khe áo.'),
                                       ('Mây đen kéo đến từng mảng, bầu trời như bị nuốt chửng.'),
                                       ('Không khí loãng dần khi càng tiến lên đỉnh núi.'),
                                       ('Cả không gian như chìm vào trạng thái lặng im đáng sợ.');

SELECT 'SEED LORE COMPLETED' AS status;