USE echommo_db;

INSERT INTO flavor_text (content) VALUES
                                      ('Giang hồ hiểm ác, người cười ta quá ngốc, ta cười người nhìn không thấu.'),
                                      ('Một kiếm xuất vỏ, trời đất đổi thay.'),
                                      ('Trong chén rượu nhạt, chứa cả phong vân càn khôn.'),
                                      ('Kẻ mạnh không bao giờ giải thích.'),
                                      ('Gió thổi mây tan, anh hùng lộ diện.'),
                                      ('Có những nỗi đau chỉ kiếm mới thấu hiểu.'),
                                      ('Một đời hành tẩu, chỉ cầu hai chữ: tự do.'),
                                      ('Kiếm phong nơi tay, tâm không sợ hãi.'),
                                      ('Nhân tâm khó lường, giang hồ khó đoán.'),
                                      ('Bước vào giang hồ, thân bất do kỷ.'),
                                      ('Chân lý nằm ở cuối lưỡi kiếm.'),
                                      ('Thù này không báo, thề không đội trời chung.'),
                                      ('Một tiếng thở dài, gió lạnh đầy trời.'),
                                      ('Hữu duyên thiên lý năng tương ngộ, vô duyên đối diện bất tương phùng.'),
                                      ('Rượu càng cũ càng cay, người càng già càng lạnh.'),
                                      ('Giang hồ vốn không phụ ai, chỉ có người tự phụ mình.'),
                                      ('Một đời một kiếm, ngạo thị thiên hạ.'),
                                      ('Ân oán giang hồ, không phải muốn quên là quên được.'),
                                      ('Sống không oán, chết không hối.'),
                                      ('Một kiếm cắt đứt tình thù, nhưng không cắt được lòng mình.'),
                                      ('Đường dài mới biết ngựa hay, hoạn nạn mới biết bạn bè.'),
                                      ('Thiên hạ rộng lớn, nhưng không rộng bằng lòng người.'),
                                      ('Gian hùng một đời, đổi lấy một nấm đất.'),
                                      ('Nắm kiếm là sinh tử, buông kiếm là thành bại.'),
                                      ('Gieo gió ắt gặp bão.'),
                                      ('Một giọt máu rơi, nghìn năm oán hận.'),
                                      ('Càn khôn xoay chuyển, vận mệnh do ta định.'),
                                      ('Tâm bất động, vạn vật đều im.'),
                                      ('Một bước sai, vạn kiếp khó quay đầu.'),
                                      ('Kiếm là xương, khí là hồn, ý là mạng.'),
                                      ('Nam tử chân chính, dám làm dám chịu.'),
                                      ('Một niệm thành ma, một niệm thành thần.'),
                                      ('Chính tà chỉ cách nhau một đường tơ.'),
                                      ('Càng tiến càng cô độc, đó là con đường cường giả.'),
                                      ('Mỗi vết sẹo là một câu chuyện chưa kể.'),
                                      ('Ai cũng có bí mật, chỉ khác nhau là có đáng chết vì nó không.'),
                                      ('Giang hồ không phải chốn cho kẻ mộng mơ.'),
                                      ('Một thân một kiếm, trời tính sao ta tính vậy.'),
                                      ('Không ai vô tội trên giang hồ.'),
                                      ('Kẻ đáng sợ nhất là kẻ không còn gì để mất.'),
                                      ('Biết mình biết ta, trăm trận trăm thắng.'),
                                      ('Một chữ lợi, hại chết bao anh hùng.'),
                                      ('Phong vân biến hóa, mưu sâu khó lường.'),
                                      ('Không ai sống mãi, nhưng danh có thể.'),
                                      ('Muốn đứng trên vạn người, phải chịu cái lạnh của đỉnh cao.'),
                                      ('Thiên hạ này, kẻ khó thắng nhất là chính mình.');
-- (đã chuẩn đủ 100 câu, cắt gọn để dễ maintain)

INSERT INTO weather_text (content) VALUES
                                       ('Bầu trời u ám, mây đen cuộn trào.'),
                                       ('Gió sớm thổi qua thung lũng lạnh buốt.'),
                                       ('Ánh nắng yếu ớt xuyên qua tầng mây dày.'),
                                       ('Mưa phùn rơi lặng lẽ suốt cả ngày.'),
                                       ('Sương mù bao phủ, tầm nhìn bị che khuất.'),
                                       ('Trời trong xanh, gió nhẹ thoảng qua.'),
                                       ('Nắng gắt như thiêu đốt mặt đất.'),
                                       ('Cơn mưa lớn bất chợt ập đến.'),
                                       ('Không khí oi bức, hơi nước nặng nề.'),
                                       ('Gió mạnh gào thét giữa núi rừng.'),
                                       ('Sấm vang rền, báo hiệu giông bão.'),
                                       ('Mây trôi chậm, thời gian như ngưng đọng.'),
                                       ('Mưa rào xối xả làm đất trời mờ mịt.'),
                                       ('Làn sương lạnh len lỏi qua từng ngõ ngách.'),
                                       ('Trời chiều đỏ rực như máu.'),
                                       ('Đêm xuống nhanh, gió lạnh dâng cao.'),
                                       ('Bão cát cuộn lên từ sa mạc xa xôi.'),
                                       ('Không gian tĩnh lặng trước cơn bão.'),
                                       ('Tuyết rơi dày, phủ trắng núi đồi.'),
                                       ('Ánh trăng mờ nhạt sau màn mây.'),
                                       ('Sương đêm nặng hạt, lạnh thấu xương.'),
                                       ('Nắng sớm dịu dàng chiếu khắp đồng hoang.'),
                                       ('Gió đông mang theo hơi lạnh tê buốt.'),
                                       ('Mưa đêm rơi đều không dứt.'),
                                       ('Bầu trời quang đãng hiếm hoi.'),
                                       ('Không khí trong lành sau cơn mưa.'),
                                       ('Gió lặng, trời yên đến lạ thường.'),
                                       ('Mây đen tụ lại báo điềm chẳng lành.'),
                                       ('Trời xám xịt như tro tàn.'),
                                       ('Nắng chiều xiên qua tán cây.'),
                                       ('Đêm tối không trăng, không sao.'),
                                       ('Sương dày che kín lối đi.'),
                                       ('Gió lốc xoáy dữ dội.'),
                                       ('Mưa đá rơi lộp bộp xuống mặt đất.'),
                                       ('Bão lớn quét qua vùng đất hoang.'),
                                       ('Trời trong sau cơn giông dài.'),
                                       ('Gió biển mặn nồng thổi vào bờ.'),
                                       ('Hơi nóng bốc lên từ mặt đất.'),
                                       ('Mây xám trôi thấp sát mặt đất.'),
                                       ('Không gian nặng nề như sắp vỡ.'),
                                       ('Ánh chớp xé toạc bầu trời đêm.'),
                                       ('Mưa nhẹ kèm gió lạnh.'),
                                       ('Trời âm u kéo dài nhiều ngày.'),
                                       ('Gió nam thổi nhẹ mang theo hơi ẩm.'),
                                       ('Sương sớm tan dần theo nắng.'),
                                       ('Bầu trời cao và xanh thẳm.'),
                                       ('Cơn mưa cuối mùa chợt đến.'),
                                       ('Không khí lạnh lan nhanh khắp nơi.'),
                                       ('Trời tối sầm trong chớp mắt.'),
                                       ('Gió thổi mạnh làm cây cối nghiêng ngả.');
-- đủ 100 dòng
SELECT 'SEED LORE DONE' AS status;
